/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package redsocialproyectoii;

import java.awt.Dimension;
import java.util.Calendar;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

public class Navegacion extends javax.swing.JFrame {
    private String usuario;
    //variable para reutillizar instancia
    private static Navegacion instanciaUnica;
    AgregarTweet comment;
    AdminUsuarios busquedaLista = new AdminUsuarios();
    private Navegacion() {
        initComponents();
        comment = new AgregarTweet();
        busquedaLista.AgregarUsuario("Samuel", "samuel_lara", "feo", "Masculino", 18, "01-01-1999");
        busquedaLista.AgregarUsuario("Alice", "alice123", "password", "Femenino", 25, "01-01-1999");
    }
    
    public static Navegacion getInstancia() {
        if (instanciaUnica == null) {
            instanciaUnica = new Navegacion();
        }
        return instanciaUnica;
    }
    
    boolean comparar(){
        
        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelType = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTweet = new javax.swing.JTextArea();
        btnTwitt = new javax.swing.JButton();
        lblNameUser = new javax.swing.JLabel();
        PanelBtn = new javax.swing.JPanel();
        btnInteract = new javax.swing.JButton();
        btnHashtags = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        PanelSearch = new javax.swing.JPanel();
        txtBusqueda = new javax.swing.JTextField();
        listaUsers = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        PanelPost = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelType.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        areaTweet.setColumns(20);
        areaTweet.setRows(5);
        areaTweet.setLineWrap(true);
        areaTweet.setWrapStyleWord(true);
        areaTweet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                areaTweetKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(areaTweet);

        btnTwitt.setText("Comentar");
        btnTwitt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwittActionPerformed(evt);
            }
        });

        lblNameUser.setText("jLabel1");

        javax.swing.GroupLayout PanelTypeLayout = new javax.swing.GroupLayout(PanelType);
        PanelType.setLayout(PanelTypeLayout);
        PanelTypeLayout.setHorizontalGroup(
            PanelTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTypeLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(PanelTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTypeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTwitt))
                    .addGroup(PanelTypeLayout.createSequentialGroup()
                        .addComponent(lblNameUser)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelTypeLayout.setVerticalGroup(
            PanelTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTypeLayout.createSequentialGroup()
                .addComponent(lblNameUser)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTwitt)
                .addContainerGap())
        );

        PanelBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnInteract.setText("Interacciones");

        btnHashtags.setText("Hashtags");

        btnClose.setText("Cerrar Sesion");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnProfile.setText("Mi Perfil");

        javax.swing.GroupLayout PanelBtnLayout = new javax.swing.GroupLayout(PanelBtn);
        PanelBtn.setLayout(PanelBtnLayout);
        PanelBtnLayout.setHorizontalGroup(
            PanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBtnLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(PanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnClose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInteract, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBtnLayout.createSequentialGroup()
                        .addComponent(btnProfile)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBtnLayout.createSequentialGroup()
                        .addComponent(btnHashtags)
                        .addGap(38, 38, 38))))
        );
        PanelBtnLayout.setVerticalGroup(
            PanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBtnLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnProfile)
                .addGap(103, 103, 103)
                .addComponent(btnInteract)
                .addGap(103, 103, 103)
                .addComponent(btnHashtags)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(37, 37, 37))
        );

        PanelSearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnSearch.setText("🔍");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSearchLayout = new javax.swing.GroupLayout(PanelSearch);
        PanelSearch.setLayout(PanelSearchLayout);
        PanelSearchLayout.setHorizontalGroup(
            PanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSearchLayout.createSequentialGroup()
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch))
                    .addComponent(listaUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelSearchLayout.setVerticalGroup(
            PanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listaUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelPost.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout PanelPostLayout = new javax.swing.GroupLayout(PanelPost);
        PanelPost.setLayout(PanelPostLayout);
        PanelPostLayout.setHorizontalGroup(
            PanelPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelPostLayout.setVerticalGroup(
            PanelPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelPost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelPost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void areaTweetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_areaTweetKeyTyped
        int caracteresDisponibles=140;
        if (areaTweet.getText().length()>=caracteresDisponibles) {
            evt.consume();
            JOptionPane.showMessageDialog(areaTweet, "Solo se permite 140 caracteres. ");
        }
    }//GEN-LAST:event_areaTweetKeyTyped

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        listaUsers.removeAllItems();  // Limpiar el JComboBox antes de cada búsqueda
    
        String busqueda = txtBusqueda.getText().toLowerCase(); // Obtener el texto de búsqueda y convertir a minúsculas
        System.out.println("Buscando: " + busqueda); // Imprime lo que estás buscando
        for (Usuario Admin : busquedaLista.Admin) {
            if (Admin != null) {
                String nombreUsuario = Admin.toString().toLowerCase(); // Obtener el nombre del usuario y convertir a minúsculas
                System.out.println("Comparando con: " + nombreUsuario); // Imprime el nombre del usuario
                if (nombreUsuario.contains(busqueda)) {
                    listaUsers.addItem(Admin.toString()); // Añadir el usuario al JComboBox si contiene la subcadena
                }
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        Inicio volver = Inicio.getInstance();
        volver.setVisible(true);
        volver.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnTwittActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwittActionPerformed
        Calendar cal= Calendar.getInstance();
        int dia=cal.get(Calendar.DATE);
        int mes= cal.get(Calendar.MONTH)+1;
        int anio= cal.get(Calendar.YEAR);
        String usr=lblNameUser.getText();
        String tweet = areaTweet.getText().trim();
        String fecha = dia+"/"+mes+"/"+anio;
        if(!tweet.isEmpty()){
            if(comment.buscarTweets(tweet)==null){
                //variable booleana, ya que retorna true/false
                boolean agregado = comment.agregarTweet(usuario, tweet, fecha);
                if (agregado) {
                     JTextArea tweetArea = new JTextArea("Usuario: " + usuario + "\n" +
                                                    "Publicación: " + tweet + "\n" +
                                                    "Fecha: " + fecha);
                    tweetArea.setLineWrap(true);
                    tweetArea.setWrapStyleWord(true); 
                    tweetArea.setEditable(false); 
                    JScrollPane scrollPane = new JScrollPane(tweetArea);
                    scrollPane.setPreferredSize(new Dimension(300, 60));
                    tweetArea.setPreferredSize(new Dimension(300, 60));
                    PanelPost.setLayout(new BoxLayout(PanelPost, BoxLayout.Y_AXIS));
                    PanelPost.add(scrollPane);
                    PanelPost.revalidate(); 
                    PanelPost.repaint();
                    areaTweet.setText("");
                }else{
                    JOptionPane.showMessageDialog(null, "Error al agregar el tweet.");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Este tweet ya existe");
            }
        }else{
            JOptionPane.showMessageDialog(null, "No has escrito nada!");
        }
    }//GEN-LAST:event_btnTwittActionPerformed

    public void setlblNameUser(String usuario){
        this.usuario=usuario;
        lblNameUser.setText(usuario);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBtn;
    private javax.swing.JPanel PanelPost;
    private javax.swing.JPanel PanelSearch;
    private javax.swing.JPanel PanelType;
    private javax.swing.JTextArea areaTweet;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnHashtags;
    private javax.swing.JButton btnInteract;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnTwitt;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNameUser;
    private javax.swing.JComboBox<String> listaUsers;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}