/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Xiangqi;
import Xiangqi.Master;
import javax.swing.JOptionPane;

/**
 *
 * @author Hp
 */
public class ElegirOP extends javax.swing.JFrame {

 public Master mas;
 
    public ElegirOP(Master mast) {
        initComponents();
        mas=mast;
        this.setTitle("Elegir Oponente");
        this.setLocationRelativeTo(null);
        
        
        for (int i = 0; i <mas.NumUsers; i++) {
            if (!mas.UsuarioActual.getUser().equals(mas.users[i].getUser())) {
                BoxUsers.addItem(mas.users[i].getUser());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JugadorNegro = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ElegirOp = new javax.swing.JLabel();
        BoxUsers = new javax.swing.JComboBox<>();
        btnSeleccionar = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();

        JugadorNegro.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        JugadorNegro.setForeground(new java.awt.Color(0, 0, 0));
        JugadorNegro.setText("Jugador Negro: P2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));

        ElegirOp.setFont(new java.awt.Font("Old English Text MT", 3, 24)); // NOI18N
        ElegirOp.setForeground(new java.awt.Color(0, 0, 0));
        ElegirOp.setText("Elegir Oponente");

        BoxUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxUsersActionPerformed(evt);
            }
        });

        btnSeleccionar.setForeground(new java.awt.Color(0, 0, 0));
        btnSeleccionar.setText("Seleccionar Oponente");
        btnSeleccionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSeleccionarMouseClicked(evt);
            }
        });

        btnReturn.setText("Return");
        btnReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReturnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReturn)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ElegirOp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BoxUsers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSeleccionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnReturn)
                .addGap(63, 63, 63)
                .addComponent(ElegirOp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BoxUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSeleccionar)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoxUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxUsersActionPerformed

    private void btnSeleccionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeleccionarMouseClicked
        // TODO add your handling code here:
        if (BoxUsers.getSelectedItem() != null) {
            for (int i = 0; i < mas.NumUsers; i++) {
                if (BoxUsers.getSelectedItem().equals(mas.users[i].getUser())) {
                    mas.UsuarioRival = mas.users[i];

                    new Tablero_Xiangqi(mas).setVisible(true);
                    this.dispose();
                    this.setLocationRelativeTo(null);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, elegir un Rival");
        }

    }//GEN-LAST:event_btnSeleccionarMouseClicked

    private void btnReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReturnMouseClicked
        // TODO add your handling code here:
        new MainMenu(mas).setVisible(true);
        this.dispose();
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnReturnMouseClicked

    /**
     * @param args the command line arguments
     */
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxUsers;
    private javax.swing.JLabel ElegirOp;
    private javax.swing.JLabel JugadorNegro;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
